name: Pipeline linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: actions/checkout@v2

        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.14'

        - name: install dependencies
          run: npm install

        - name: Run linter
          run: npm run lint
